{{- if .Values.hiveInitJob.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-job-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all_objects_labels" . | nindent 4 }}
type: Opaque
data:
  db-user: {{ include "postgres.hive.user" . | b64enc | quote }}
  db-password: {{ include "postgres.hive.password" . | b64enc | quote }}
  db-url: {{ include "postgres.psql.connection.url" . | b64enc | quote }}
  jdbc-url: {{ printf "jdbc:postgresql://%s:%s/%s%s" (include "postgres.host" .) (include "postgres.port" .) .Values.hive.db (include "jdbcParams" (dict "Values" .Values "separator" "&")) | b64enc | quote }}
{{- end }}